name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        ref: csgo

    - name: Configure CMake (Win32)
      run: cmake -B build -A Win32

    - name: Build Osiris Release
      run: cmake --build build --config Release

    - name: Upload Osiris DLL
      uses: actions/upload-artifact@v4
      with:
        name: Osiris-CSGO-DLL
        path: |
          build/Release/Osiris.dll
          build/Osiris.dll
