name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        ref: csgo

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Osiris Win32
      run: msbuild Osiris.sln /p:Configuration=Release /p:Platform=Win32

    - name: Upload Osiris DLL
      uses: actions/upload-artifact@v4
      with:
        name: Osiris-CSGO-Win32
        path: |
          Release/Osiris.dll
          bin/Release/Osiris.dll
          build/Release/Osiris.dll
